name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gatsby-site
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache Gatsby .cache folder
        uses: actions/cache@v1
        id: gatsby-cache-folder
        with:
          path: ./gatsby-site/.cache
          key: ${{ runner.os }}-gatsby-site-gatsby-cache
          restore-keys: |
            ${{ runner.os }}-gatsby-site-gatsby-cache

      - name: Cache Gatsby public folder
        uses: actions/cache@v1
        id: gatsby-public-folder
        with:
          path: ./gatsby-site/public
          key: ${{ runner.os }}-gatsby-site-gatsby-public
          restore-keys: |
            ${{ runner.os }}-gatsby-site-gatsby-public

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Gatsby build
        run: npm run build -- --log-pages
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gatsby-site/public
          force_orphan: true